#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# tilix fix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# automatic stuff after config...
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/simon/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# #############################################################

# colors
#autoload -U colors && colors
# prompt
#autoload -U promptinit
#promptinit
#prompt elite2
#PROMPT="%{$fg[red]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg_no_bold[yellow]%}%1~ %{$reset_color%}%#"
#RPROMPT="[%{$fg_no_bold[yellow]%}%?%{$reset_color%}]"
# fish-like syntax highlighting
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
########################################################################
#

# zsh options
setopt extended_glob
set -o shwordsplit
# golang
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH/bin
export EDITOR=vim

# cdpath
export CDPATH=".:~:/home/simon/go/src/github.com/zmnpl/:/home/simon/SynologyDrive/:/home/simon/workspace"

# android sdk
export PATH=$PATH:$HOME/workspace/android-sdk-linux/platform-tools

# own scripts path
export PATH=$PATH:~/helperscripts
export PATH=$PATH:~/helperscripts/backup

# pico-8
export PATH=$PATH:~/SynologyDrive/Linux/pico-8

# general stuff
alias grep-key-code='___grep-key-code'
function ___grep-key-code {
	xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}

# alias xflock4='light-locker-command -l'
alias xflock4='sxlock'
alias cp='cp -v'
alias rm='rm -v'
alias feh='feh -T simondefault'
alias fotosnap='sudo rsnapshot -v daily'
alias fucking-reboot='sudo shutdown -r now'
alias fuckoff='sudo shutdown -h now'
alias n8='systemctl suspend'
alias fuz='fzf --preview="cat {}" --preview-window=right:70%:wrap'
alias fuzed='vim `fuz`'
alias winvm='/usr/lib/virtualbox/VirtualBox --comment "win7" --startvm "866c04cd-1173-4a34-9d7e-1ea5bb2f03c2"'
# notes
alias nedit=fuzed
function note {
	vim ~/SynologyDrive/Notes/$1.md
}

# audio

# list sinks if not valid anymore
# pacmd list-sinks | grep -e 'name:' -e 'index:'
function pcaudio-headphones {
	echo "set-default-sink alsa_output.usb-FiiO_DigiHug_USB_Audio-01.analog-stereo" | pacmd
}
function pcaudio-speakers {
	echo "set-default-sink alsa_output.pci-0000_30_00.3.analog-stereo" | pacmd
}


# pacman aliases
alias kick='sudo pacman -Rns'
alias whatsinaur='pacman -Qqm'
alias whatsinstalled='pacman -Qet | grep -v "^xorg" | grep -v "^xfce"'

# git aliases
alias "git-lg"="git log --oneline"
alias "git-graph"="git log --graph"
alias "gadd"="git add --all"
alias "gommit"="git commit --m"

# urxvt
alias urxvtoptions="urxvt --help 2>&1| sed -n '/:  /s/^ */! URxvt*/gp'"

# steam temporary after nvidia driver bug
#alias steam="__GLVND_DISALLOW_PATCHING=1 steam"

# ssh aliases
source ~/SynologyDrive/Linux/ssh_alias.zsh

# note taking
function ___find_note {
	grep -rn --exclude-dir="*evernote*" --exclude-dir="*archiv*" "$1" ~/SynologyDrive/Notes
}
alias "findnote"='___find_note'


# crypto
# keychain
alias keychain-unlock='eval `keychain --eval --agents ssh id_rsa_space`'
# close crypt drives
alias cryptCloseUsbBackup='sudo cryptsetup close /dev/mapper/backupusb'

# useful
#alias "listext" = `find . -type f | sed -e 's/.*\.//' | sed -e 's/.*\///' | sort | uniq -c | sort -rn`


#screenfetch
neofetch
